# Generated by Django 5.1.4 on 2025-05-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='account_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'E-Sewa'), ('khalti', 'Khalti'), ('mo_banking', 'Mobile Banking'), ('connect_ips', 'connectIPS'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_category',
            field=models.CharField(choices=[('medical', 'Medical'), ('nature', 'Natural Clamities'), ('animal', 'Animal'), ('rites', 'Rites of Passage'), ('other', 'Other')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_for',
            field=models.BooleanField(default=False),
        ),
    ]
