# Generated by Django 5.1.4 on 2025-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_account_type_campaign_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='account_type',
            field=models.BooleanField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('other', 'Other')], default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='project_for',
            field=models.BooleanField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('other', 'Other')], default=False),
        ),
    ]
